# Proyecto A: Optimización en la Planeación de Transporte Vehicular Urbana Para LogistiCo

## Integrantes

- Barrera Toro, Javier Steven
- Borbon Holguin, Luis Alfredo
- Rolon Toloza, Julian Santiago

## 1.  Formulación Matemática del Modelo

### 1.1. Definición de Conjuntos

- D: Conjunto de centros de distribución:
$$D = \{D1, D2, D3\}$$

- C: Conjunto de zonas de entrega.
$$C = \{C1, C2, C3\}$$

- N Conjunto de todos los nodos.
$$N = C \cup D$$

- V: Conjunto de vehículos disponibles.
$$ V = \{V1, V2, V3\} $$

- A: Conjunto de rutas posibles entre nodos, definidos por:
$$ A = \{(i, j) \in N \times N | i ̸= j\} $$

Además, para facilitar el recorrido sobre los conjuntos definimos el siguientes indices.

- $i, j \in N$: índices para representar los nodos (clientes y centros de distribución).
- $k \in V$: Índice para los vehículos disponibles.

### 1.2. Definición de parametros:

Los parámetros que se definen para el modelo son los siguientes: 

- $q_k$: La capacidad máxima de carga del vehículo $k$.
- $c_i$: La capacidad máxima del almacenamiento en el centro de distribución $i \in D$.
- $d_i$: Demanda del cliente $i \in C$.

Para las distancias y tiempos entre los nodos se definen los siguientes. 
- $d_{ij}$: Distancia entre los nodos $i$ y $j$.
- $t_{ij}$: Tiempo de viaje entre los nodos $i$ y $j$.

En cuanto a los costos:
- $c_{ij}$: Costo de transporte entre nodos $i$ y $j$.
- $f_k$: Costo de flete por kilómetro de cada vehículo $k$. 
- $v_k$: Costo por kilómetro del vehículo $k$. 

**TODO**: Agregar justificación.

https://www.motor.com.co/actualidad/Nueva-alza-en-la-gasolina-en-Colombia-aumento-95-pesos-en-febrero-2025-20250203-0002.html

https://cabify.com/co/tarifas/bogota#p-envios

Los costos que se asumen constantes durante todo el proceso son los siguientes. 

- Costo de mantenimiento ($M$): \$600 por km.
- Precio del combustible ($G$): \$4.145 por km.
- Tarifa del servicio ($P$): \$600 por km
- Consumo del combustible: 0,1 litros por km. Lo que significa 0,1 * G = 0,1*$15.000 = 1,500$
- Costo total por km = M+G+1.500

### 1.3. Variables de decisión y variables:

Las variables de decisión que se utilizarán en el modelo son las siguientes. 

1. $X_{i,j,k}$: Es una matriz binaria que indica si el vehículo $k$ vaija del nodo $i$ al nodo $j$. 1 si el vehículo $k$ recorre el arco de $i$ a $j$, de lo contrario $X_{i,j,k} = 0$.
2. $q_{i,k}$: Cantidad de carga que transporta el vehículo $k$ cuando llega al nodo $i$. Es una variable continua que se mantiene en los límites de capacidad del vehículo. 
3. $t_{i,k}$: Tiempo en que el vehículo $k$ llega al nodo $i$. Es una variable continua.

En cuanto a variables auxiliares que serán utiles para el problema se las plantean las siguientes dos.
1. $d_{i, k}$: Es la demanda atendida en el nodo $i$ por el vehículo $k$.
2. $u_{i, k}$: Orden de visita del nodo $i$ por el vehículo $k$ para eliminar subtours usando MTZ, lo cual garantiza la conectividad del recorrido.


### 1.4. Restricciones

1. La restricción de flujo, garantiza que si un vehiculo entra a un nodo también sale del mismo.
$$
\sum_{i \in N} X_{ij} = \sum_{k \in N} X_{jk}, \forall j \in C, \forall t
$$

2. La capacidad del vehículo, garantiza que la cantidad de productos transportados nunca supera la capacidad máxima de carga.
$$
\sum_{(i, j) \in N} d_j X_{tij} \leq Q, \forall t
$$

3. Un cliente se atiende exactamente una vez, para simplificar el problema. 
$$
\sum_{i \in N} \sum_{t \in T} X_{tij} = 1, \forall j \in C
$$

4. Restricción sobre la cantidad transportada a un cliente no supere la demanda.
$$
Q_{tij} \leq d_j X_{tij}, \forall t \in T, \forall i \in N, \forall j \in C
$$

5. La carga transportada por un vehículo no supera la capacidad máxima.
$$
\sum_{j \in C} Q_{tij} \leq Q_{max} X_{tij}, \forall t \in T, \forall i \in N
$$

6. La cantidad entregada a un cliente $j$ sea igua a la demanda requerida $d_j$.
$$
\sum_{t \in T} \sum_{(i,j) \in N} Q_{tij} = d_j
$$

7. Un vehiculo no transporta mas que su capacidad
$$
Q_{tij} \leq C X_{tij}, \forall t \in T, \forall (i,j) \in N
$$

8. Conservación de flujo con las cantidades entregadas en cada uno de los nodos
$$
\sum_{j\in N} Q_{tij} - \sum_{j \in N} Q_{tij} = d_i, \forall t \in T, \forall i \in N \\ \{ 0 \}
$$

9. Cada vehículo no puede recorrer más distancia que la permitida por su autonomía máxima
$$
\sum_{(i,j) \in N} d_{ij} X_{tij} \leq A_{\max} , \forall t \in T
$$

10. Cada vehículo no puede transportarmás carga de la que permite su capacidad
$$
\sum_{(i,j) \in N} q_i X_{tij} \leq Q_{\max}, \forall t \in T
$$

11. La cantidad total de productos enviados desde un centro de distribución no puede superar su capacidad
$$
\sum_{(i,j) \in N} q_j X_{tij} \leq S_i, \forall t \in T
$$

12. Para evitar ciclos en las rutas de los vehiculos definimos $u_i$ y aplicamos la restricción de Miller-Tucker-Zemlin (MTZ):
$$
u_i - u_j + |N| X_{tij} \leq |N| - 1, \forall (i,j) \in N
$$


## 2. Función Objetivo y Proceso de indagación

Para definir esta función objetivo, se llevó a cabo un análisis relacionado con la optimización de rutas y problemas logísticos. La formulación se diseñó con el objetivo de reducir al máximo los costos de transporte, los cuales están determinados por la distancia que se recorre y los costos operativos como tarifas de flete, mantenimiento y consumo de combustible.
El propósito es reducir al mínimo el costo total de transporte. Este costo se calcula teniendo en cuenta el valor por kilómetro recorrido, multiplicado por la distancia total que recorre cada vehículo en los trayectos seleccionados.

La función objetivo está definida como:

$$
\min\left(\sum_{t \in T} \sum_{(i,j) \in N} C_{ij} \times X_{tij} \right)
$$

## 3. Preprocesamiento de datos y análisis

En este punto se nos pide realizar la transformación de los datos ya que contamos con latitud y longitud pero se necesita el tiempo y las distancia. Una primera aproximación podría ser pensar en calcular la distancia euclidiana de estos puntos. Sin embargo, esto tiene un problema ya que obtenemos la distancia minima entre dos puntos en un plano, ignorando completamente calles y edificios, se podría pensar que los vehiculos atraviesan todo a su paso desde un centro de distribución hacía el punto de entrega, lo cual es incorrecto. Además de realizar la conversión a información que entienda el modelo se debe resolver este problema. Una solución bastante buena para este problema es utilizar el servicio de [`Distance Matrix API`](https://developers.google.com/maps/documentation/distance-matrix/overview) de Google Cloud, aprovechando que aún tenemos los créditos de arquisoft. 

In [4]:
try:
    import googlemaps
except Exception:
    print("googlemaps module not found")

En la siguiente celda se definen el código necesario para generar la matriz de distancias y la matriz de tiempo. Una vez se tiene esto se pueden calcular las matrices de costos facilmente unicamente multiplicando el valor que se definio por la matriz, gracias a que se esta trabajando con `numpy` el valor se multiplica de una vez por todas las entradas de la matriz.

In [5]:
# import numpy as np

# # Reemplaza con tu clave de API de Google Maps
# API_KEY = "AIzaSyDTD8eB5wVQyBDTBWUfA7aU9taCZ-T5nHg"
# gmaps = googlemaps.Client(key=API_KEY)

# ubicaciones = [
#     ("CD1", "Bodega Norte", 4.7110, -74.0721),
#     ("CD2", "Bodega Sur", 4.6050, -74.0835),
#     ("CD3", "Bodega Este", 4.6700, -74.0300),
#     ("C1", "Catalina", 4.6486, -74.0608),
#     ("C2", "Rodrigo", 4.7333, -74.0700),
#     ("C3", "Luis", 4.7000, -74.0200),
# ]

# # Crear un diccionario para mapear nombres a coordenadas
# coords = {loc[0]: (loc[2], loc[3]) for loc in ubicaciones}
# n = len(ubicaciones)  # Número total de ubicaciones

# # Inicializar matrices para distancias y tiempos
# distancias = np.zeros((n, n))
# tiempos = np.zeros((n, n))

# # Función para obtener distancia y tiempo entre dos ubicaciones
# def obtener_distancias_tiempos(origen, destino):
#     resultado = gmaps.distance_matrix(
#         origins=[origen],
#         destinations=[destino],
#         mode="driving",
#         units="metric"
#     )
#     distancia = resultado["rows"][0]["elements"][0]["distance"]["value"] / 1000  # km
#     tiempo = resultado["rows"][0]["elements"][0]["duration"]["value"] / 60  # minutos
#     return distancia, tiempo

# # Llenar la matriz de distancias y tiempos
# for i in range(n):
#     for j in range(n):
#         if i != j:  # No calcular la distancia de un nodo a sí mismo
#             dist, time = obtener_distancias_tiempos(coords[ubicaciones[i][0]], coords[ubicaciones[j][0]])
#             distancias[i, j] = dist
#             tiempos[i, j] = time

In [11]:
# # Imprimir matrices
# print("Matriz de Distancias (km):")
# print(distancias)

# print("\nMatriz de Tiempos (minutos):")
# print(tiempos)

Matriz de Distancias (km):
[[ 0.    14.504 15.445  9.23   2.727  7.516]
 [15.759  0.    18.667  7.623 18.211 17.42 ]
 [14.612 19.088  0.    10.077 17.339 14.046]
 [ 8.559  8.891  9.901  0.    12.34   9.802]
 [ 2.738 18.011 17.824 12.716  0.    10.247]
 [ 8.028 19.008 15.818 10.552  8.585  0.   ]]

Matriz de Tiempos (minutos):
[[ 0.         30.73333333 41.73333333 23.1         6.21666667 21.38333333]
 [30.25        0.         47.01666667 21.21666667 35.56666667 37.76666667]
 [38.21666667 47.76666667  0.         29.73333333 44.45       38.61666667]
 [24.7        25.05       31.13333333  0.         30.1        29.61666667]
 [ 6.06666667 35.85       48.06666667 31.6         0.         29.33333333]
 [23.53333333 43.25       46.48333333 32.98333333 27.05        0.        ]]


Además, dado que se esta buscando minimizar la función objetivo, no se puede utilizar tal cual la matriz anterior, se deben reemplazar los valores de 0 por un valor lo suficientemente grande como lo puede ser $999999$. 

In [12]:
# Matriz de Distancias (km)
distancias = [
    [999999, 14.504, 15.445, 9.23, 2.727, 7.516],
    [15.759, 999999, 18.667, 7.623, 18.211, 17.42],
    [14.612, 19.088, 999999, 10.077, 17.339, 14.046],
    [8.559, 8.891, 9.901, 999999, 12.34, 9.802],
    [2.738, 18.011, 17.824, 12.716, 999999, 10.247],
    [8.028, 19.008, 15.818, 10.552, 8.585, 999999]
]

# Matriz de Tiempos (minutos)
tiempos = [
    [999999, 30.73333333, 41.73333333, 23.1, 6.21666667, 21.38333333],
    [30.25, 999999, 47.01666667, 21.21666667, 35.56666667, 37.76666667],
    [38.21666667, 47.76666667, 999999, 29.73333333, 44.45, 38.61666667],
    [24.7, 25.05, 31.13333333, 999999, 30.1, 29.61666667],
    [6.06666667, 35.85, 48.06666667, 31.6, 999999, 29.33333333],
    [23.53333333, 43.25, 46.48333333, 32.98333333, 27.05, 999999]
]

## 4. Ejemplos ilustrativos

**TODO**: Que se cumplan todas y otro ejemplo en el que una restricción no se cumpla.

## 5. Justificación y discusión

**TODO**: Suposiciones que hay que hacer al modelo para simplificarlo. 